# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:oZR5kE1SheC0Wl+MZanaHpPc09SuKYJjjVsZZ+hD6097QOImiSzTKpjAYp3L8BJdcS5C3vXeattVfijTqd03ysZvL51lB5/vTY9sgum8ObJlBYV/pxuuRIz2n0uIx1DICKToBg1weYD468BfmP6ruVwIsa9amzNWCOznkxwrzNIazYSjgzIKl5rnAvTdOAZJYAvDR61e/EzWq88Y9vpG+uMYaCw1vDugMFanPseI/aQ5Rav3Hg==,iv:Kx0/U4guZ1slqDoj3RmJQ/LL6hHUV7x+bn9fNnRImD8=,tag:xuyobgWRqYMUK6pLeCS+vg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age18d0zptjd0x2hw2my2scu2ynv66lfenwvplhf95qtzr2my93gtg7q7g5g4r
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQQW01SjBDWmsrWnBiYmwv
        eDArWk9DaC9pZXdrWHA4ZHZzOHhOYnh0YlNJCkRKZzBnSHErK2NLZnhXdThBaTgx
        ck9QK2dMRkcwNzRuSUZDbVdTZG5wcDAKLS0tIExYSnJGM0E2amtVRVRtZ2p2OW9q
        U2thQzYwRmJ0NExsZ3RQd3dJV1ZMNVkKm4BZnpryZDwV5XUzHZOavHZz/gJqRhFL
        9Kn3CQQiSsysu8AfSppdsJXd8GaMmd8VeDTTfhNffNjqVzr1n/vnaw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-15T19:59:06Z"
  mac: ENC[AES256_GCM,data:16vs/DVxgCsJcEVaUmnqXR11J6JTciKLW5aQpAttrnEBzEd+lLtzfTPayWMKy87JLc2hHBHXtOz0gU+zGwQVHTAzDVraP1LWQxt866YDm7fmnQow79giQKm1USSj0+2efOKdtnWwsdxL2MJvIaEavjf/3Wo3g/PrjFwbz7yyFsQ=,iv:rJTHBaxp2c9bZ+ut7CwJV+7zrfIO/SntH/YrkoL/j4M=,tag:u4F+RyTh9asqVH+8GC9Pig==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
