# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ""
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age18d0zptjd0x2hw2my2scu2ynv66lfenwvplhf95qtzr2my93gtg7q7g5g4r
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmcUx4TDZHSHRGc29jQTlO
        RzFwS25OYW1Jb2llMFZ1eFY4Ly9JQjM1ZmpvCm92YnV1TkRZWUxKMFZlWnpTbGVv
        SFpZa0RiSUtSUi9UbTlGY2JVaEtkLzgKLS0tIDJreEV4WGlzVDlSV3FSZVA4T1Yw
        alhhbVFOVHhWV3dXcnVPaTE5RVZydkkKobTPfAMOpNPJ0tPIygqAo0hvtXWBykYz
        a6HRs6kVVINfYk9H3ilJU83tmuj6LMUWVl9ujw4enc9IWrt36l+EOA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-15T19:59:06Z"
  mac: ENC[AES256_GCM,data:LnWP3lv5OM7+PgXZslcXApgvMNFOwErTK/vjfwbEvtgA9QIA2IlPOred4hxF5lR39KJh2dfNwTXSCQZcLL0Cn/I8t61Tv6B05QEgyTaHmI5gyQbbaCeMq+X9vGFMNgaPuxO3AG/e8w/RAKLjxIdayi82JxR7NhENd7rfMsIKvP8=,iv:k3/uFsvi+ZD9rwFmC0HSmle3RdrE3f4jeB72On1FRx8=,tag:j2ZE8jbe//HD6bWFv4vo8w==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
