openapi: 3.1.0
info:
  title: Server API
  version: 1.0.0
servers:
  - url: http://localhost:3000
paths:
  /:
    get:
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Hello World!
